localhost:
  hosts:
    127.0.0.1:
  vars:
    ansible_connection: local
    ansible_python_interpreter: /Users/alireza/AWS.git/venv/bin/python

mainServer:
  hosts:
    54.84.117.224:
  vars:
    ansible_user: ec2-user
    ansible_become: true
