localhost:
  hosts:
    127.0.0.1:
  vars:
    ansible_connection: local
    ansible_python_interpreter: /Users/alireza/AWS.git/venv/bin/python

mnServer:
  hosts:
    alireza.me:
  vars:
    ansible_user: ec2-user
    ansible_become: true
    ansible_python_interpreter: /usr/bin/python3
