localhost:
  hosts:
    127.0.0.1:
  vars:
    ansible_connection: local

# server is being configured for now, access via IP
# to bootstrap essential services/daemons
mnServer:
  hosts:
    #54.84.117.224:
    2600:1f10:475a:be0a::27:
  vars:
    ansible_user: ec2-user
    ansible_become: true
    ansible_python_interpreter: /usr/bin/python3

# DNS is running now...
ec2Server:
  hosts:
    alireza.me:
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
