---
- hosts: mnServer 
  vars:
    # ec2Store_passwd: ""
    # -e "{ec2Store_passwd: 'MyPasswd'}"

  tasks:
  - debug:
      msg: "=> {{ ec2Store_passwd }}   Q: {{ ec2Store_passwd|quote }}"
    tags:
      - vars
      - ec2str

  - yum:
      name: httpd, mod_ssl, postfix, squid, bind, bash, tmux, socat, perl-Mail-SPF, perl-Mail-DKIM, perl-Sys-Syslog
      state: latest
    tags: ypkg

  - shell: mount| grep /ec2Store| wc -l
    args:
      executable: /bin/bash
    register: ec2Store_mountState
    tags: ec2str
  - block:
    - file:
        path: /ec2Store
        state: directory
    - shell: (cryptsetup close ec2Store || true)
        && echo {{ ec2Store_passwd|quote }} | cryptsetup create ec2Store /dev/xvdx
        && mount /dev/mapper/ec2Store /ec2Store && ln -s /ec2Store /ec2str
      args:
        executable: /bin/bash
    when: ec2Store_mountState.stdout == "0"
    tags: ec2str

  - shell: (mv /etc/{{ item }} /etc/{{ item }}___ || true)
      && (ln -s /ec2Store/{{ item }} /etc/{{ item }} || true)
    loop: ["httpd", "postfix", "squid"]
    tags: etc

  - user:
      name: "{{ item }}"
      comment: "{{ item }} User"
      shell: /sbin/nologin
    loop: ["spf", "dkim"]
    tags: usr

  - block:
    - file:
        path: /etc/systemd/system/postfix.service.d
        state: directory
    - copy:
        content: "[Service]\nPIDFile=/ec2str/spool/postfix/pid/master.pid\n"
        dest: /etc/systemd/system/postfix.service.d/override.conf
        mode: 0644
    - shell: systemctl daemon-reload
    tags: pid

  - shell: /ec2str/dkimproxy/init-script start
    tags: dkim

  - block:
    - shell: hostname ec2svr && echo "export PS1='\h \w \\\$ '" >> /root/.bashrc
    - systemd:
        state: restarted
        name: "{{ item }}"
        enabled: yes
        masked: no
      loop: ["httpd", "postfix", "squid", "rsyslog", "named"]
    tags: run

  - copy:
      content: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAgEAq3sysHMyiP78WExRpUEK78ANJS5dZLzPAotoh3gjTt8mNFLYWXFg9wL26Cr2WND1FId76bZ0+TBmW1ZJlEImXE7IfbKfVSNmUBv2v5fYUMyXtNrm2q9HWNRP3Me2WcLgOrjs/ShrMp9B2T1rVQBwV5YRptZwin8K3526XRiRTPCo50ZSfHmErpf7h0AnEasKWC3Nj2T1NPOm13uLS9mFHCsNBH6W1UXLQHQZL7Ycaz0VT1T5R5WkAwXKw8hLS2aMIS43Om0AnGsGDJq6rFN1wj2hd/gJIestlNW4EByaIHJETxy9gMQGEeEkWwRG1hw6+2v1/CST8odo8cBL6H1Y+RpYw1RSnwx2sGzmwJrAhrBk8qNO2DdvTPlYO1jKLXp279BNMqelgxy/iXR3/gG3Z/mM/8XiIH4fi0wYOQIDLwAKm+n7GGKAYCJTwd+OC3/jxpTOQRtj9xhv422OAdUgTctKmJyXjm+KgiecI5QTqzZi2vXxMJnoXIZltM4bSRW6zUNZefenQ8wSx8zpTdBpcBfHXQR3xQeNHQ8IJIFW/bKyk/mywi3yWYPs5auJ5BRSWFAkGdCdFYaFnhzaLUuWFapPJ3E+mDj8J2uNN8f98RBQzT3oO63t1EDamwXydlBHB8JRFFfS+k22wcrWGhbbpOXP6JUgZI7o9D5N/8tHuHE= MyRSA\necdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBABYrSEK/OsEcWv/f/S3/QbtMOlXvsRRRYpdALh5ZBI0nBdZkkJxyK4t8yWTD1yHgngEHk9GN3QugDoll2rk7CxqtAFCqBuyOHccIHYq8FDlgd/lMLwqVQtPN1kQ4s52XSPl5xzujd2pvmlXWz5nzYMxvczHfW3wAHvcdsi8QOPT4tj7nQ== MyEC\n"
      dest: /root/.ssh/authorized_keys
      mode: 0400
    tags: key
