---
- hosts: localhost
  gather_facts: false
  pre_tasks:
    - include_vars: vars.yml

  tasks:
  - ec2_eip:
      ip: "{{ eip }}"
      device_id: "{{ msi }}"
      allow_reassociation: yes

  - ec2_vol:
      id: "{{ ec2str }}"
      instance: "{{ msi }}"
      device_name: "/dev/xvdx"
      delete_on_termination: false
