---
- hosts: localhost
  gather_facts: false
  pre_tasks:
    - include_vars: vars.yml

  tasks:
  - ec2_eip:
      ip: "{{ eip }}"
      device_id: "{{ nic }}"
      allow_reassociation: yes
      in_vpc: true

  - ec2_eni:
      eni_id: "{{ nic }}"
      instance_id: "{{ msi }}"
      device_index: 1
      delete_on_termination: false
      attached: true

  - ec2_vol:
      id: "{{ ec2str }}"
      instance: "{{ msi }}"
      device_name: "/dev/xvdx"
      delete_on_termination: false
