---
- hosts: localhost
  environment:
  gather_facts: false

  tasks:
  - ec2_eip_info:
    tags: eip

  - ec2_eni_info:
      filters:
    tags: eni

  - ec2_instance_info:
    tags: ec2

  - block:
    - include_vars: vars.yml
    - ec2_vol_info:
        region: "{{ region }}"
    tags: vol
